#!/usr/bin/env bash
# server - login
eval $(ssh-agent -s)
ssh-add  ~/.ssh/school
# web-server 0
ssh ubuntu@54.172.62.130
# web-server 1
# ssh ubuntu@54.196.34.67
# web-server 2
# ssh ubuntu@54.160.80.89
