#!/usr/bin/env bash
# Display a list of currently running processes in a user-oriented format with hierarchy
ps axjf | awk 'BEGIN {printf "%-10s %-6s %-5s %-6s %-5s %-5s %-5s %-10s %-8s %s\n", "USER", "PID", "%CPU", "%MEM", "VSZ", "RSS", "TTY", "STAT", "START", "COMMAND"} 
             {printf "%-10s %-6s %-5s %-6s %-5s %-5s %-5s %-10s %-8s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}'
