#!/usr/bin/env bash
# Bash script that creates the file /var/run/myscript.pid containing its PID

echo "$$" > /var/run/myscript.pid
sudo trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
sudo trap 'echo "Y U no love me?!"' SIGINT
sudo trap 'rm /var/run/myscript.pid; exit' SIGQUIT
while true; do echo "To infinity and beyond"; sleep 2; done