#!/usr/bin/env bash
# This script is displaying The content of the current directory
# Where only the part of the name after the first dash is displayed 
for _ in *
do
    echo "$_" | cut -d'-' -f2
done
