#!/usr/bin/env bash
# Bash script that accepts one argument
# script should run the whoami command under the user passed as an argument

# Check if the script is provided with exactly one argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Run the `whoami` command as the specified user
sudo -u "$1" whoami
