#!/usr/bin/env bash
# Now that you have successfully connected to your server, we would also like to join the party.
# Add the SSH public key below to your server so that we can connect using the ubuntu user.

ssh -i ~/.ssh/school ubuntu@89.0.142.86
